// angular/todo/src/app/components/account/account.component.ts
import { Component, Input, OnInit } from '@angular/core'
import { FormBuilder } from '@angular/forms'
import { Router } from '@angular/router'
import { AuthSession } from '@supabase/supabase-js'
import { Profile, SupabaseService } from 'src/app/services/supabase.service'

@Component({
  selector: 'app-account',
  templateUrl: './account.component.html',
  styleUrls: ['./account.component.css'],
})
export class AccountComponent implements OnInit {
  loading = false
  profile!: Profile
  session!: AuthSession

  updateProfileForm = this.formBuilder.group({
    username: '',
    website: '',
    avatar_url: '',
  })

  constructor(private readonly supabase: SupabaseService, private formBuilder: FormBuilder, private router: Router) { }

  async ngOnInit(): Promise<void> {
    this.session = this.supabase.session!
    await this.getProfile()

    const { username, website, avatar_url } = this.profile
    this.updateProfileForm.patchValue({
      username,
      website,
      avatar_url,
    })
  }

  async getProfile() {
    try {
      this.loading = true
      const { user } = this.session
      let { data: profile, error, status } = await this.supabase.profile(user)

      if (error && status !== 406) {
        throw error
      }

      if (profile) {
        this.profile = profile
      }
    } catch (error) {
      if (error instanceof Error) {
        alert(error.message)
      }
    } finally {
      this.loading = false
    }
  }

  async updateProfile(): Promise<void> {
    try {
      this.loading = true
      const { user } = this.session

      const username = this.updateProfileForm.value.username as string
      const website = this.updateProfileForm.value.website as string
      const avatar_url = this.updateProfileForm.value.avatar_url as string

      const { error } = await this.supabase.updateProfile({
        id: user.id,
        username,
        website,
        avatar_url,
      })
      if (error) throw error
    } catch (error) {
      if (error instanceof Error) {
        alert(error.message)
      }
    } finally {
      this.loading = false
    }
  }

  signOut() {
    this.supabase.signOut().then(() => window.localStorage.removeItem('sb-ksrrqdsagxlaijrlqqzx-auth-token')).then(() => this.router.navigate(['/login']))
  }

  get avatarUrl() {
    return this.updateProfileForm.value.avatar_url as string
  }

  async updateAvatar(event: string): Promise<void> {
    this.updateProfileForm.patchValue({
      avatar_url: event,
    })
    await this.updateProfile()
  }
}
<form [formGroup]="updateProfileForm" (ngSubmit)="updateProfile()" class="form-widget">
    <app-avatar [avatarUrl]="this.avatarUrl" (upload)="updateAvatar($event)"> </app-avatar>
    <div>
        <label for="email">Email</label>
        <input class="input disabled" id="email" type="text" [value]="session.user.email" disabled />
    </div>
    <div>
        <label for="username">Name</label>
        <input class="input" formControlName="username" id="username" type="text" />
    </div>
    <div>
        <label for="website">Website</label>
        <input class="input" formControlName="website" id="website" type="url" />
    </div>

    <div>
        <button type="submit" class="primary" [disabled]="loading">
            {{ loading ? 'Loading ...' : 'Update' }}
        </button>
    </div>

    <div>
        <button class="secondary" (click)="signOut()">Sign Out</button>
    </div>
</form>

// vue/todo/src/views/Account.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { supabase } from '../supabase'
import Avatar from '@/components/Avatar.vue'
import type { AuthSession } from '@supabase/supabase-js';
import { useRouter } from 'vue-router';

const session = JSON.parse(window.localStorage.getItem('sb-tsqfpecssujjoeglqusv-auth-token') || '{}') as AuthSession

const loading = ref(true)
const username = ref('')
const website = ref('')
const avatar_url = ref('')
const router = useRouter()

onMounted(() => {
    getProfile()
})

async function getProfile() {
    try {
        loading.value = true
        const { user } = session

        let { data, error, status } = await supabase
            .from('profiles')
            .select(`username, website, avatar_url`)
            .eq('id', user.id)
            .single()

        if (error && status !== 406) throw error

        if (data) {
            username.value = data.username
            website.value = data.website
            avatar_url.value = data.avatar_url
        }
    } catch (error) {
        console.log(error)
    } finally {
        loading.value = false
    }
}

async function updateProfile() {
    try {
        loading.value = true
        const { user } = session

        const updates = {
            id: user.id,
            username: username.value,
            website: website.value,
            avatar_url: avatar_url.value,
            updated_at: new Date(),
        }

        let { error } = await supabase.from('profiles').upsert(updates)

        if (error) throw error
    } catch (error) {
        console.log(error)
    } finally {
        loading.value = false
    }
}

async function signOut() {
    try {
        loading.value = true
        let { error } = await supabase.auth.signOut()
        if (error) throw error
        router.push('/login')
    } catch (error) {
        console.log(error)
    } finally {
        loading.value = false
    }
}
</script>

<template>
    <form @submit.prevent="updateProfile">
        <Avatar v-model:path="avatar_url" @upload="updateProfile" size="10" />
        <div>
            <label for="email">Email</label>
            <input class="input disabled" id="email" type="text" :value="session.user.email" disabled />
        </div>
        <div>
            <label for="username">Name</label>
            <input class="input" v-model="username" type="text" />
        </div>
        <div>
            <label for="website">Website</label>
            <input class="input" v-model="website" id="website" type="url" />
        </div>

        <div>
            <button type="submit" class="primary" :disabled="loading">
                {{ loading ? 'Loading ...' : 'Update' }}
            </button>
        </div>

        <div>
            <button class="secondary" @click="signOut" :disabled="loading">Sign Out</button>
        </div>
    </form>
</template>
