// vue/todo/src/components/Avatar.vue
<script setup lang="ts">
import { ref, toRefs, watch } from 'vue'
import { supabase } from '../supabase'

const props = defineProps({
    path: { type: String, required: true },
    size: { type: String, required: true }
})
const { path, size } = toRefs(props)

const emit = defineEmits(['upload', 'update:path'])
const uploading = ref(false)
const src = ref('')
const files = ref()

const downloadImage = async () => {
    try {
        const { data, error } = await supabase.storage.from('avatars').download(path.value)
        if (error) throw error
        src.value = URL.createObjectURL(data)
    } catch (error) {
        console.error('Error downloading image: ', error)
    }
}

const uploadAvatar = async (evt: any) => {
    files.value = evt.target.files
    try {
        uploading.value = true
        if (!files.value || files.value.length === 0) {
            throw new Error('You must select an image to upload.')
        }

        const file = files.value[0]
        const fileExt = file.name.split('.').pop()
        const filePath = `${Math.random()}.${fileExt}`

        let { error: uploadError } = await supabase.storage.from('avatars').upload(filePath, file)

        if (uploadError) throw uploadError
        emit('update:path', filePath)
        emit('upload')
    } catch (error) {
        console.log(error)
    } finally {
        uploading.value = false
    }
}

watch(path, () => {
    if (path.value) downloadImage()
})
</script>

<template>
    <div class="flex justify-center items-center flex-col">
        <img v-if="src" :src="src" alt="Avatar" class="avatar image" />
        <div v-else class="avatar no-image"></div>
        <div class="upload">
            <label for="single">
                {{ uploading ? 'Uploading ...' : 'Upload picture' }}
            </label>
            <input style="visibility: hidden;position: absolute" type="file" id="single" accept="image/*"
                @change="uploadAvatar" :disabled="uploading" />
        </div>
    </div>
</template>

// angular/todo/src/app/components/avatar/avatar.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core'
import { SafeResourceUrl, DomSanitizer } from '@angular/platform-browser'
import { SupabaseService } from 'src/app/services/supabase.service'

@Component({
  selector: 'app-avatar',
  templateUrl: './avatar.component.html',
  styleUrls: ['./avatar.component.css'],
})
export class AvatarComponent {
  _avatarUrl: SafeResourceUrl | undefined
  uploading = false

  @Input()
  set avatarUrl(url: string | null) {
    if (url) {
      this.downloadImage(url)
    }
  }

  @Output() upload = new EventEmitter<string>()

  constructor(private readonly supabase: SupabaseService, private readonly dom: DomSanitizer) { }

  async downloadImage(path: string) {
    try {
      const { data } = await this.supabase.downLoadImage(path)
      if (data instanceof Blob) {
        this._avatarUrl = this.dom.bypassSecurityTrustResourceUrl(URL.createObjectURL(data))
      }
    } catch (error) {
      if (error instanceof Error) {
        console.error('Error downloading image: ', error.message)
      }
    }
  }

  async uploadAvatar(event: any) {
    try {
      this.uploading = true
      if (!event.target.files || event.target.files.length === 0) {
        throw new Error('You must select an image to upload.')
      }

      const file = event.target.files[0]
      const fileExt = file.name.split('.').pop()
      const filePath = `${Math.random()}.${fileExt}`

      await this.supabase.uploadAvatar(filePath, file)
      this.upload.emit(filePath)
    } catch (error) {
      if (error instanceof Error) {
        alert(error.message)
      }
    } finally {
      this.uploading = false
    }
  }
}
<div class="flex justify-center items-center flex-col">
    <div>
        <img *ngIf="_avatarUrl" [src]="_avatarUrl" alt="Avatar" class="avatar image" />
    </div>
    <div *ngIf="!_avatarUrl" class="avatar no-image"></div>
    <div class="upload">
        <label for="single">
            {{ uploading ? 'Uploading ...' : 'Upload' }}
        </label>
        <input style="visibility: hidden;position: absolute" type="file" id="single" accept="image/*"
            (change)="uploadAvatar($event)" [disabled]="uploading" />
    </div>
</div>
